class Constants{




  static final String j  = '[{"position": "1","name": "Mercury","image": "http://space-facts.com/wp-content/uploads/mercury-transparent.png","velocity": "47","distance": "58","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "2","name": "Venus","image": "http://space-facts.com/wp-content/uploads/venus-transparent.png","velocity": "35","distance": "108","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "3","name": "Earth","image": "http://space-facts.com/wp-content/uploads/earth-transparent.png","velocity": "29","distance": "149","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "4","name": "Mars","image": "http://space-facts.com/wp-content/uploads/planets_images-transparent.png","velocity": "24","distance": "227","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "5","name": "Jupiter","image": "http://space-facts.com/wp-content/uploads/jupiter-transparent.png","velocity": "13","distance": "778","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "6","name": "Saturn","image": "http://space-facts.com/wp-content/uploads/saturn-transparent.png","velocity": "9","distance": "1426","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "7","name": "Uranus","image": "http://space-facts.com/wp-content/uploads/uranus-transparent.png","velocity": "6","distance": "2870","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "8","name": "Neptune","image": "http://space-facts.com/wp-content/uploads/neptune-transparent.png","velocity": "5","distance": "4498","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."},'
      '{"position": "9","name": "Sun","image": "http://pngimg.com/uploads/sun/sun_PNG13424.png","velocity": "220","distance": "0","description": "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016."}]';
}